# Generated by Django 3.2.9 on 2022-03-27 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chapter_3', '0002_auto_20220327_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='seller',
            name='vehicles',
            field=models.ManyToManyField(blank=True, related_name='vehicle_sellers', related_query_name='vehicle_seller', to='chapter_3.Vehicle', verbose_name='Vehicles'),
        ),
        migrations.AlterField(
            model_name='engine3',
            name='vehicle_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_engine2', to='chapter_3.vehicle_model', verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Business Name'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engine_vehicle', to='chapter_3.engine', verbose_name='Engine'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_vehicle', to='chapter_3.vehicle_model', verbose_name='Model'),
        ),
    ]
